BEGIN;

-- A request without X-User-Id is also treated as a guest.
CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  role varchar(20) NOT NULL DEFAULT 'client',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_role_check CHECK (role IN ('guest', 'client', 'admin'))
);

CREATE TABLE IF NOT EXISTS public.series (
  id varchar(100) PRIMARY KEY,
  title varchar(255) NOT NULL,
  original varchar(255) NOT NULL,
  year integer NOT NULL CHECK (year >= 1888),
  end_year integer CHECK (end_year IS NULL OR end_year >= year),
  rating numeric(3, 1) CHECK (rating IS NULL OR rating BETWEEN 0 AND 10),
  age varchar(10) NOT NULL DEFAULT '',
  duration varchar(50) NOT NULL DEFAULT '',
  genres text[] NOT NULL DEFAULT '{}',
  director varchar(255) NOT NULL DEFAULT '',
  description text NOT NULL,
  image text NOT NULL,
  src text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.movie_genres (
  movie_id integer NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  genre_id integer NOT NULL REFERENCES public.genres(id) ON DELETE CASCADE,
  PRIMARY KEY (movie_id, genre_id)
);

CREATE TABLE IF NOT EXISTS public.reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id integer NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  rating integer NOT NULL CHECK (rating BETWEEN 1 AND 10),
  comment text NOT NULL CHECK (length(trim(comment)) > 0),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (movie_id, user_id)
);

CREATE INDEX IF NOT EXISTS reviews_movie_id_idx ON public.reviews(movie_id);
CREATE INDEX IF NOT EXISTS reviews_user_id_idx ON public.reviews(user_id);

COMMIT;
